name: Trigger Deployment for Staging

on:
  push:
    branches: [staging]

jobs:
  trigger-deployment:
    name: Trigger Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Webhook
        uses: distributhor/workflow-webhook@v1
        env:
          webhook_url: 'https://forge.laravel.com/servers/316757/sites/1142111/deploy/http?token=${{ secrets.STAGING_DEPLOYMENT_TOKEN }}'
          webhook_secret: ${{ secrets.STAGING_DEPLOYMENT_TOKEN }}
