name: Deploy Staging to Firebase

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]

jobs:
  create-envfile:
    name: Set Environment
    runs-on: ubuntu-latest
    steps:
    - name: Create .env file
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_VUE_APP_I18N_LOCALE: "en"
        envkey_VUE_APP_I18N_FALLBACK_LOCALE: "en"
        envkey_VUE_APP_MULTICONTRACT: "bancorcnvrtr"
        envkey_VUE_APP_SMARTTOKENCONTRACT: "smarttokens1"
        envkey_VUE_APP_USDSTABLE: "stable.sx"
        envkey_VUE_APP_NETWORKCONTRACT: "thisisbancor"
        envkey_VUE_APP_AFFILIATE: ${{ secrets.VUE_APP_AFFILIATE }}
        envkey_VUE_APP_BLOCKNATIVE: ${{ secrets.VUE_APP_BLOCKNATIVE }}
        file_name: .env
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: staging
      - name: Install Dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: dist
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:staging
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
